### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by zaubara** [souly1/ion-number-picker#2]
Hello,

I bought the directive and it does exactly what I wanted it to - so thank you. It looks and feels great!

However, I wanted to use multiple (sometimes maybe 40 or more, inside an ng-repeat) on the same page, and found that it brought the device to a halt.
I fixed a few of the issues in the minified code, but that's obviously far from optimal.

The two-way-bindings (4 of them for each possible number) are unnecessary. The height calculation with innerHeight eats lots of the performance as well.
When openend, theres a div created for each number - so if I want to allow, say, 1-400, ng-repeat creates all of the divs when opened. It would be nice if they're added (and removed, or maybe even  better: edited) on scroll; or maybe while having a few of the divs already created.
The created scroll divs (each with a unique id) are appended to the body and never removed, same goes for the listeners. They should be removed when the directive gets destroyed, and maybe even reused (so the divs don't need to be recreated each time).

Do you think you'll get around to fixing the issues, or send me the unminified sources? Thanks!

**Comment by souly1** [comment]
Hi Martin, thanks for the input.
I'll look into it and see what can be done.

Thanks

**Comment by souly1** [comment]
@zaubara , just to make sure, the performance issues you experience are only on opening drawer right? once it is open everything works smoothly?

**Comment by zaubara** [comment]
Hey, thanks for your quick reply!
Exactly, once it's open the scrolling is smooth - there's a delay when opening the drawer, and when opening the view that contains (multiple) pickers. The biggest culprits I already mentioned, best would probably be to create a view with 20+ pickers and 400+ numbers each and checking the cpu tab in chrome :)

I could send you my hastily-fixed min.js, if that's of any help? (although I'm sure I missed a few spots ^^)

**Comment by souly1** [comment]
Hi @zaubara , did you download the last version and have you tried the binding strategies?
Update me how it worked out.

Thanks

**Comment by zaubara** [comment]
Hey @souly1 , thanks for the update - I did, and it's a bit better, thanks.
I tried the staging one - I haven't noticed it to be disabled for me, and the performance seems to be close to before. I still had to remove the divs from the DOM (since it's getting huge very quickly), but now scrolling sometimes starts to lag. It's a bit weird, I must admit. Might be an issue with your last change, I did notice you switched from two-way-bindings to doing that in the directive; using one time bindings would've probably been easier, as I'm not sure the stuff gets released properly.
I think the best approach would be to reuse a created picker instead of creating new ones, and maybe more importantly, not creating one div for each number - but instead only creating ~10 and replacing the content of the divs on scroll (like they do it in a collection-repeat in ionic, but that implementation it's own issues).

edit - I overloaded the disabled-class, so yes - it does work and I can style that now, so it's more responsive - thanks!

**Comment by souly1** [comment]
Hi @zaubara , 
As to the binding, the new version does not use any of angular/ionic to build the DOM and register events.
In regards to collection-repeat, this component does not use ionics scrolling component but has its own where dynamically loading the list caused issues with jumps in the current element displayed or causing lag in the scroll while elements where still loading, that's why this solution was eventually selected.
The reason I do not remove the DOM element is to improve load time of the next open, but I understand this is a scenario which might not be relevant to others and rather have the element and its listeners removed, therefor I'll be adding an option to delete the element when drawer closed.

I'm not sure what you mean with overloading the disabled class (?) and do things work better now?

edit - version released

**Comment by zaubara** [comment]
Every version gets better, thank you!
I do, however, have a last request - some of the listeners seem to survive the destruction of elements - opening/closing it a few times brings the plugin to a halt.

<img width="569" alt="bildschirmfoto 2017-03-28 um 18 19 38" src="https://cloud.githubusercontent.com/assets/6575317/24415872/2e32b884-13e3-11e7-8886-003134522e9a.png">

I realize that my usage is possibly quite far off from the usual scenarios, but it's practically impossible to fix that stuff myself on minified code.

Thanks again!

**Comment by souly1** [comment]
Hi @zaubara , thanks for the input. I'll look into this.
Thanks
